mounts:
  arm:
    model: rb5_850e
    parent_slot: base
    parent_frame: base_link
    xyz:
    - 0.0
    - 0.0
    - 0.095
    rpy:
    - 0.0
    - 0.0
    - 1.570796
  endeffector:
    model: onrobot_rg2
    parent_slot: arm
    parent_frame: tcp
    xyz:
    - 0.0
    - 0.0
    - 0.0
    rpy:
    - 0.0
    - 0.0
    - -1.570796
  sensor1:
    model: d405
    parent_slot: endeffector
    parent_frame: rg2_hand
    xyz:
    - 0.02
    - 0.0
    - 0.03
    rpy:
    - 0.0
    - 0.0
    - 0.0
  sensor2:
    model: d435i
    parent_slot: base
    parent_frame: base_link
    xyz:
    - 0.0
    - -0.14
    - 0.6
    rpy:
    - 0.0
    - 0.0
    - 1.570796
models:
  base: scout_v2
  arm: rb5_850e
  endeffector: onrobot_rg2
  sensor1: d405
  sensor2: d435i
